### ISSUE TITLE
Deprecation notice in ember-bootstrap 4

### ISSUE THREAD

**Issue by basz** [kaliber5/ember-bootstrap-changeset-validations#24]
Extending BsForm is deprecated in ember-bootstrap 4. How would this addon need to change to keep working?

`Extending from ember-bootstrap component classes is not supported, and might break anytime. Detected subclassing of <BsForm> component.`
```
2VM5842:94 Ember Inspector (Deprecation Trace): Extending from ember-bootstrap component classes is not supported, and might break anytime. Detected subclassing of <BsForm> component.

        at HANDLERS.<computed> (https://localhost:4201/assets/vendor.js:43285:9)
        at invoke (https://localhost:4201/assets/vendor.js:43297:9)
        at Object.deprecate (https://localhost:4201/assets/vendor.js:43253:28)
        at Class.target.init (https://localhost:4201/assets/vendor.js:171258:94)
        at initialize (https://localhost:4201/assets/vendor.js:35968:9)
        at Function.create (https://localhost:4201/assets/vendor.js:36517:9)
        at Function.superWrapper (https://localhost:4201/assets/vendor.js:37641:22)
        at Function.create (https://localhost:4201/assets/vendor.js:108845:29)
        at Function.superWrapper [as create] (https://localhost:4201/assets/vendor.js:37641:22)
```

**Comment by simonihmig** [comment]
Yeah, we need to fix this here. In the long term we should come up with better APIs to integrate form validation that don't rely on subclassing. In the meantime however there is an escape hatch specifically added for those "privileged" addons that are allowed to use this, as we pledge to keep them updated and working. So [here in the deprecation code](https://github.com/kaliber5/ember-bootstrap/blob/master/addon/utils/deprecate-subclassing.js) there is this `__ember-bootstrap_subclass` flag we can add to the component instance to silence the deprecation.

Up for a PR? 😁

**Comment by basz** [comment]
PR https://github.com/kaliber5/ember-bootstrap-changeset-validations/pull/25
